In [2]:
from transformers import BertTokenizer, BertForQuestionAnswering

tokenizer = BertTokenizer.from_pretrained('deepset/bert-base-cased-squad2')

In [3]:
tokenizer

BertTokenizer(name_or_path='deepset/bert-base-cased-squad2', vocab_size=28996, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True)

In [4]:
model = BertForQuestionAnswering.from_pretrained('deepset/bert-base-cased-squad2')

In [5]:
example_text = "GPT-3 came in 2020"
example_question = "When did GPT-3 come"

In [ ]:
tokenized_inputs = tokenizer(example_question,example_text,return_tensors='pt')

In [7]:
tokenized_inputs

{'input_ids': tensor([[  101,  1332,  1225, 15175,  1942,   118,   124,  1435,   102, 15175,
          1942,   118,   124,  1338,  1107, 12795,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [125]:
text = '''The name Vatican City was first used in the Lateran Treaty, signed on 11 February 1929, which established the modern city-state named after Vatican Hill, the geographic location of the state within the city of Rome. "Vatican" is derived from the name of an Etruscan settlement, Vatica or Vaticum, located in the general area the Romans called Ager Vaticanus, "Vatican territory".[24]
The Italian name of the city is Città del Vaticano or, more formally, Stato della Città del Vaticano, meaning 'Vatican City State'. Its Latin name is Status Civitatis Vaticanae; this is used in official documents by the Holy See, the Church and the Pope.
Vatican City contains religious and cultural sites such as St. Peter's Basilica, the Sistine Chapel, and the Vatican Museums. They feature some of the world's most famous paintings and sculptures. The unique economy of Vatican City is supported financially by donations from the faithful, by the sale of postage stamps and souvenirs, fees for admission to museums, and sales of publications. Vatican City has no taxes and items are duty-free.'''

# question = ["Vetican is derived from ?","The Italian name of the city is?","what happened on 11 February 1929?"]
question = "what happened on 11 February 1929?"
tokenized_inputs = tokenizer(question,text,return_tensors='pt')

In [126]:
tokenized_inputs.input_ids.shape

torch.Size([1, 254])

In [127]:
import torch
with torch.no_grad():
    outputs = model(**tokenized_inputs)

In [128]:
outputs.start_logits.shape

torch.Size([1, 254])

In [129]:
outputs.keys()

odict_keys(['start_logits', 'end_logits'])

In [130]:
answer_start_index = outputs.start_logits.argmax(-1)
answer_end_index = outputs.end_logits.argmax(-1)

In [131]:
answer_start_index

tensor([17])

In [132]:
answer_end_index

tensor([20])

In [133]:
predict_answer_tokens = tokenized_inputs.input_ids[0,answer_start_index:answer_end_index+1]

In [134]:
predict_answer_tokens

tensor([1103, 2611, 1389, 6599])

In [135]:
tokenizer.decode(predict_answer_tokens)

'the Lateran Treaty'